# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do
  lane :beta do
    setup_ci if ENV['CI']
    match(type: 'appstore', readonly: true)
    build_app(scheme: "SNUTT", configuration: "Release")
  #  upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
