source "https://rubygems.org"

gem "fastlane"

# Load plugins from Pluginfile if it exists
plugins_path = File.join(File.dirname(__FILE__), 'Scripts', 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
