name: xcodebuild

on:
  pull_request:
    paths:
      - 'SNUTT-2022/**'
      - ".github/workflows/build.yml"

jobs:
  build-and-test:
    name: ${{ matrix.command }} on Xcode ${{ matrix.xcode }}, ${{ matrix.macos }}
    runs-on: ${{ matrix.macos }} # os switching
    
    strategy:
      fail-fast: false # if 'true' then one failed job cancels all jobs remaining
      matrix:
        xcode: 
          - '13.2.1' # iOS 15.2
        macos: ['macos-11']
        command: ['test']
        scheme: ['SNUTT']

    steps:
    - uses: actions/checkout@v2

    - uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: ${{ matrix.xcode }}
    
    - run: xcodebuild -showsdks
    
    - uses: mxcl/xcodebuild@v1.9.2
      with:
        platform: iOS
        action: ${{ matrix.command }} 
        code-coverage: true
        scheme: ${{ matrix.scheme }}
        verbosity: xcpretty
        upload-logs: always
        configuration: Debug
        working-directory: SNUTT-2022
    