name: Build Test

on:
  pull_request:
    paths:
      - 'SNUTT-2022/**'

jobs:
  build-and-test:
    name: ${{ matrix.command }} on  ${{ matrix.platform }} (xcode ${{ matrix.xcode }}, ${{ matrix.macos }})
    runs-on: ${{ matrix.macos }} # os switching
    
    strategy:
      fail-fast: false # if 'true' then one failed job cancels all jobs remaining
      matrix:
        xcode: 
          - '13.2.1' # iOS 15.2
          - '12.5.1' # iOS 14.5
          - '12.0.1' # iOS 14.0
          - '11.2.1' # iOS 13.2.2
        macos: ['macos-11', 'macos-10.15']
        command: ['test']
        exclude:
          # excluding xcodes not present on given macOS versions
          # https://flatgithub.com/mxcl/.github/?filename=versions.json&sha=08380d108ee63e2ba27ad3ea9a2fc58010e383c3
          - macos: 'macos-11'
            xcode: '12.0.1'
          - macos: 'macos-11'
            xcode: '11.2.1'
          - macos: 'macos-10.15'
            xcode: '13.2.1'
          - macos: 'macos-10.15'
            xcode: '12.5.1'

    steps:
    - uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: ${{ matrix.xcode }}
    
    - run: |
        ls
      
    - uses: mxcl/xcodebuild@v1.9.2
      with:
        platform: iOS
        action: ${{ matrix.command }} 
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always
        working-directory: SNUTT-2022